# -*- coding: utf-8 -*-
"""AGV INTELLIGENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKsT5VPv1yM1Xlp33BG4ZtUNTE59jGfe
"""

import mesa
import random

# ENVIRONMENT

# Grid Layout
# 0: Floor
# 1: Rack
# 2: Production Line
# 3: Truck Dock
# 4: Charging Station
# 5: Doors (inaccessible before)
# 6: u/l area
# 7: only left
# 8: only right
# 9: only up
# 10: only down

LAYOUT_INFO = [
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0],
    [2, 2, 6, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 6, 3],
    [0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0],
    [2, 2, 6, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 3],
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [2, 2, 6, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 6, 3],
    [0, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0],
    [0, 4, 0, 0, 0, 6, 1, 1, 6, 10, 6, 1, 1, 6, 9, 6, 1, 1, 6, 0, 0, 0, 4, 0],
    [0, 0, 0, 0, 0, 6, 1, 1, 6, 10, 6, 1, 1, 6, 9, 6, 1, 1, 6, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 6, 1, 1, 6, 10, 6, 1, 1, 6, 9, 6, 1, 1, 6, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 6, 1, 1, 6, 10, 6, 1, 1, 6, 9, 6, 1, 1, 6, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0],
    [5, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 5],
    [5, 0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 5],
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
]

GRID_H = len(LAYOUT_INFO)
GRID_W = len(LAYOUT_INFO[0])

RACK_POSITIONS = []
CHARGING_STATIONS = []
TRUCK_DOCKS = []
DOORS = []
OBSTACLES = []
UL_AREAS = []
ONLY_LEFT = []
ONLY_RIGHT = []
ONLY_UP = []      # NUEVO
ONLY_DOWN = []    # NUEVO

for y in range(GRID_H):
  for x in range(GRID_W):
    val = LAYOUT_INFO[y][x]
    if val == 1: RACK_POSITIONS.append((x, y))
    elif val == 4: CHARGING_STATIONS.append((x, y))
    elif val == 3: TRUCK_DOCKS.append((x, y))
    elif val == 5: DOORS.append((x, y))
    elif val == 6: UL_AREAS.append((x, y))
    elif val == 7: ONLY_LEFT.append((x, y))
    elif val == 8: ONLY_RIGHT.append((x, y))
    elif val == 9: ONLY_UP.append((x, y))      # NUEVO
    elif val == 10: ONLY_DOWN.append((x, y))   # NUEVO

    if val not in (0, 4, 7, 8, 6, 9, 10): OBSTACLES.append((x, y))  # SE AGREGAN 9 Y 10 A LA EXCEPCIÓN

PRODUCTION_LINE_ENDS = [(1,2), (1, 4), (1, 6)] # LISTA DE FINAL DE LINEAS DE PRODUCCION

# GRAFO DE MOVIMIENTO
# Se construye una sola vez con el layout estático. Respeta:
#  - obstáculos fijos (racks, líneas de producción, docks, puertas)
#  - carriles de un solo sentido (7: solo izquierda / 8: solo derecha)
#  - zonas de carga y descarga (6) como nodos transitables normales

import heapq

def is_walkable(cell): # Esta celda puede usarse para desplazarse?
    x, y = cell
    val = LAYOUT_INFO[y][x]
    return val in (0, 4, 6, 7, 8, 9, 10)  # SE AGREGAN 9 Y 10

def build_movement_graph():
    graph = {}

    for y in range(GRID_H):
        for x in range(GRID_W):
            cell = (x, y)
            if is_walkable(cell):   # Si es transitable
                graph[cell] = []    # Agrega la celda como nodo del grafo

    for (x, y) in graph: # Recorre todas las celdas consideradas transitables
        val = LAYOUT_INFO[y][x]    # A cuál de mis vecinos puedo moverme?

        # VERTICAL: BLOQUEADO SI VAL O VECINO ES 10 (solo-abajo, bloquea subir)
        up = (x, y - 1) # subir
        if up in graph:
            up_val = LAYOUT_INFO[y - 1][x] # Obtiene el tipo de celda
            if val != 10 and up_val != 10: # Solo se mueve hacia arriba si la actual y la de arriban no son 10
                graph[(x, y)].append(up)

        # VERTICAL: BLOQUEADO SI VAL O VECINO ES 9 (solo-arriba, bloquea bajar)
        down = (x, y + 1) # bajar
        if down in graph:
            down_val = LAYOUT_INFO[y + 1][x]
            if val != 9 and down_val != 9:
                graph[(x, y)].append(down)

        # HORIZONTAL: derecha
        right = (x + 1, y)
        if right in graph:
            right_val = LAYOUT_INFO[y][x + 1]
            # REGLA ORIGINAL
            ok = val not in (7, 9, 10) and right_val not in (7, 9, 10)
            # EXCEPCIÓN: U/L puede conectar lateralmente con el shaft adyacente
            # Esto permite al AGV entrar/salir del shaft hacia su access cell interior
            if not ok:
                ok = (val == 6 and right_val in (9, 10)) or (val in (9, 10) and right_val == 6)
            if ok:
                graph[(x, y)].append(right)

        # HORIZONTAL: izquierda  (misma excepción)
        left = (x - 1, y)
        if left in graph:
            left_val = LAYOUT_INFO[y][x - 1]
            ok = val not in (8, 9, 10) and left_val not in (8, 9, 10)
            if not ok:
                ok = (val == 6 and left_val in (9, 10)) or (val in (9, 10) and left_val == 6)
            if ok:
                graph[(x, y)].append(left)

    return graph

MOVEMENT_GRAPH = build_movement_graph()

# ============================================================
# GRAFO DE MOVIMIENTO PARA PERSONAS
# ============================================================
# Las personas pueden caminar libremente por piso, cargadores,
# puertas, zonas U/L y carriles, sin respetar el sentido de los
# carriles. Este grafo es independiente del MOVEMENT_GRAPH del AGV.

PERSON_WALKABLE_CODES = (0, 4, 5, 6, 7, 8, 9, 10)

def is_person_walkable(cell):
    x, y = cell
    return LAYOUT_INFO[y][x] in PERSON_WALKABLE_CODES

def build_person_movement_graph():
    graph = {}

    for y in range(GRID_H):
        for x in range(GRID_W):
            cell = (x, y)
            if is_person_walkable(cell):
                graph[cell] = []

    directions = [
        (1, 0),
        (-1, 0),
        (0, 1),
        (0, -1)
    ]

    for x, y in graph:
        for dx, dy in directions:
            neighbor = (x + dx, y + dy)
            if neighbor in graph:
                graph[(x, y)].append(neighbor)

    return graph

PERSON_MOVEMENT_GRAPH = build_person_movement_graph()

UL_AREAS_SET = set(UL_AREAS)  # lookup O(1)

# FUNCIÓN A* - AHORA LAS CELDAS U/L (6) SE TRATAN COMO BLOQUEADAS
# A MENOS QUE SEAN EXACTAMENTE EL DESTINO DE ESTA BÚSQUEDA.
# ESTO EVITA QUE UN AGV "DE PASO" ATRAVIESE UNA ZONA DE CARGA/DESCARGA
# QUE NO ES SU MISIÓN ACTUAL, SIN IMPORTAR DESDE QUÉ LADO SE ACCEDA.
def astar(start, goal, graph=MOVEMENT_GRAPH, blocked=None):
    if start == goal:
        return [start]

    blocked = blocked or set() # Si no se proporcionó un conjunto de bloqueos,
                                # lo convierte en un conjunto vacío

    # Contiene las u/l areas y las estaciones de carga, las cuales no se pueden
    # atravesar a menos de ser el destino final
    RESTRICTED_UNLESS_GOAL = UL_AREAS_SET | set(CHARGING_STATIONS)

    def is_passable(cell):
        if cell in RESTRICTED_UNLESS_GOAL and cell != goal: # Si la celda está restringida y no es el destino, no
            return False
        return True # Si la celda es el destino, o no está restringida, puede pasar

    open_set = [(manhattan(start, goal), 0, start)] # nodos por explorar
    came_from = {}        # de qué nodo se viene, permite reconstruir el camino
    g_score = {start: 0}  # costo real acumulado desde el inicio hasta cada celda
    visited = set()       # celdas que ya fueron procesadas para no rehacerlo

    while open_set:           # mientras existan nodos pendientes por explorar
        _, cost, current = heapq.heappop(open_set)  # heap saca el elemento con menor prioridad

        if current == goal:   # Si se llegó al destino
            path = [current]
            while current in came_from: # Reconstruye el camino
                current = came_from[current]
                path.append(current)
            path.reverse()
            return path # Lo devuelve en orden

        if current in visited: # Si ya se visitó esa celda la salta
            continue
        visited.add(current) # Si no la marca como visitada

        for neighbor in graph.get(current, []): # Desde la celda actual, a qué celdas puede moverse?
            if not is_passable(neighbor): # Filtra movimientos inválidos
                continue
            if neighbor in blocked and neighbor != goal:
                continue

            # Calcula el nuevo costo
            tentative_g = cost + 1   # Cada movimiento cuesta 1
            if tentative_g < g_score.get(neighbor, float("inf")): # Se llegó a este vecino con un costo menor que el que se conocía anteriormente??
                g_score[neighbor] = tentative_g # Cuánto costó llegar
                came_from[neighbor] = current   # Desde dónde
                f_score = tentative_g + manhattan(neighbor, goal) # Fórmula clásica de A*
                heapq.heappush(open_set, (f_score, tentative_g, neighbor)) # Agrega el vecino a los nodods que A* debe explorar
                # Los nodos con menor f_score tienen prioridad

    return None #Si no existe ningún camino

# ============================================================
# A* PARA PERSONAS
# ============================================================
# Usa el grafo libre de personas. No restringe zonas U/L,
# cargadores, puertas ni sentidos de carril.
def astar_person(start, goal, graph=PERSON_MOVEMENT_GRAPH, blocked=None):
    if start == goal:
        return [start]

    blocked = blocked or set()

    open_set = [(manhattan(start, goal), 0, start)]
    came_from = {}
    g_score = {start: 0}
    visited = set()

    while open_set:
        _, cost, current = heapq.heappop(open_set)

        if current == goal:
            path = [current]
            while current in came_from:
                current = came_from[current]
                path.append(current)
            path.reverse()
            return path

        if current in visited:
            continue

        visited.add(current)

        for neighbor in graph.get(current, []):
            if neighbor in blocked:
                continue

            tentative_g = cost + 1

            if tentative_g < g_score.get(neighbor, float("inf")):
                g_score[neighbor] = tentative_g
                came_from[neighbor] = current
                f_score = tentative_g + manhattan(neighbor, goal)
                heapq.heappush(open_set, (f_score, tentative_g, neighbor))

    return None

# FUNCIÓN MANHATTAN
def manhattan(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

# CONSTANTE GLOBAL, junto a manhattan()
DIRECTION_TO_ORIENTATION = {(0, -1): 0, (1, 0): 90, (0, 1): 180, (-1, 0): 270, }

# FUNCIÓN: RESOLVE_OPERATIONAL_CELL
# DESCRIPCIÓN: DADA LA POSICIÓN LÓGICA DE UN RECURSO (RACK, LÍNEA, DOCK), DEVUELVE LA CELDA
# TRANSITABLE DESDE LA QUE UN AGV PUEDE OPERARLO. SI EL RECURSO YA ESTÁ SOBRE UNA CELDA
# TRANSITABLE (CASO DE LAS LÍNEAS DE PRODUCCIÓN), SE DEVUELVE ESA MISMA CELDA.
# NOTA: AHORA ES UNA FUNCIÓN GLOBAL, NO UN MÉTODO DEL MODELO, PORQUE SE NECESITA AL
# CONSTRUIR LOS RECURSOS, ANTES DE QUE EXISTAN LAS MISIONES.
def resolve_operational_cell(target):
    if target in MOVEMENT_GRAPH:
        return target
    x, y = target
    candidatos = [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
    # PRIORIDAD: SOLO SE OPERA UN RECURSO DESDE SU ZONA DE CARGA/DESCARGA (6)
    for c in candidatos:
        if c in MOVEMENT_GRAPH and LAYOUT_INFO[c[1]][c[0]] == 6:
            return c
    return None


# FUNCIÓN: COMPUTE_OPERABLE_CELLS
# DESCRIPCIÓN: A* TRATA LAS ZONAS U/L Y LOS CARGADORES COMO INTRANSITABLES SALVO QUE SEAN
# EL DESTINO. ESO SIGNIFICA QUE UNA CELDA U/D EN MEDIO DE UNA COLUMNA DE U/L NUNCA ES
# ALCANZABLE: PARA LLEGAR HABRÍA QUE ATRAVESAR OTRA U/L QUE NO ES EL DESTINO.
# EN ESTE LAYOUT ESO DEJA 8 RACKS INALCANZABLES (LOS DE EN MEDIO DE LAS COLUMNAS DE 4).
# ESTA FUNCIÓN LOS DETECTA UNA SOLA VEZ AL ARRANCAR, PARA QUE EL MODELO NUNCA PUBLIQUE
# UNA MISIÓN IMPOSIBLE. SIN ESTO, UN AGV ACEPTA LA MISIÓN, NO ENCUENTRA RUTA NUNCA Y SE
# QUEDA CONGELADO CON EL PALLET ENCIMA PARA SIEMPRE.
def compute_operable_cells():
    from collections import deque

    restricted = UL_AREAS_SET | set(CHARGING_STATIONS)
    libres = {c for c in MOVEMENT_GRAPH if c not in restricted}

    # COMPONENTE CONEXA DEL PISO LIBRE
    inicio = None
    for c in libres:
        inicio = c
        break

    comp = set()
    if inicio is not None:
        comp.add(inicio)
        cola = deque([inicio])
        while cola:
            c = cola.popleft()
            for n in MOVEMENT_GRAPH[c]:
                if n in libres and n not in comp:
                    comp.add(n)
                    cola.append(n)

    operables = set(comp)
    for c in MOVEMENT_GRAPH:
        if c in comp:
            continue
        # UNA CELDA RESTRINGIDA ES OPERABLE SI SE PUEDE ENTRAR Y SALIR DE ELLA
        # DESDE EL PISO LIBRE EN UN SOLO PASO
        entra = any(c in MOVEMENT_GRAPH[n] for n in comp)
        sale = any(n in comp for n in MOVEMENT_GRAPH.get(c, []))
        if entra and sale:
            operables.add(c)

    return operables

OPERABLE_CELLS = compute_operable_cells()


# CLASE:      PALLET AGENT
# ATRIBUTOS:  ID, STATUS
class PalletAgent(mesa.Agent):
    def __init__(self, model, pallet_id, status="stored"):
        super().__init__(model)
        self.pallet_id = pallet_id
        self.status = status


# CLASE:      RESOURCE AGENT  (CLASE BASE NUEVA)
# DESCRIPCIÓN: TODO ELEMENTO FIJO DEL ALMACÉN CON EL QUE UNA MISIÓN PUEDE INTERACTUAR:
# RACKS, LÍNEAS DE PRODUCCIÓN Y TRUCK DOCKS. TENER UNA BASE COMÚN PERMITE QUE
# out_of_service, LAS RESERVAS Y LOS FILTROS DE spawn_mission SEAN UN SOLO CAMINO DE
# CÓDIGO EN LUGAR DE TRES.
# ATRIBUTOS:
#   position      -> POSICIÓN LÓGICA DEL RECURSO EN EL GRID (LA CELDA QUE SE DIBUJA)
#   access_cell   -> CELDA TRANSITABLE DESDE LA QUE UN AGV LO OPERA (DESTINO REAL DE A*)
#   status        -> available | occupied | is_reserved | out_of_service
#   reserved_by_mission -> ID DE LA MISIÓN QUE LO TIENE APARTADO (None SI NINGUNA)
class ResourceAgent(mesa.Agent):
    kind = "resource"

    def __init__(self, model, position):
        super().__init__(model)
        self.position = position
        self.access_cell = resolve_operational_cell(position)
        self.status = "available"
        if self.access_cell is None or self.access_cell not in OPERABLE_CELLS:
            self.status = "unreachable"   # NINGÚN AGV PUEDE LLEGAR: QUEDA FUERA DEL JUEGO
        self.reserved_by_mission = None
        self.repair_at_step = None          # STEP EN EL QUE VUELVE A SERVICIO
        self.status_before_failure = None   # STATUS AL QUE REGRESA TRAS LA REPARACIÓN

    # ¿EL RECURSO ESTÁ OPERATIVO? (NI AVERIADO NI INALCANZABLE)
    def is_usable(self):
        return self.status not in ("out_of_service", "unreachable")

    # ¿ESTE RECURSO PUEDE USARSE PARA UNA MISIÓN NUEVA?
    def is_available(self):
        return self.status == "available"

    # ¿ESTE RECURSO ESTÁ DISPONIBLE PARA ESTA MISIÓN EN CONCRETO?
    # (SI YA ESTÁ RESERVADO POR ESA MISMA MISIÓN, SIGUE SIENDO SUYO)
    def is_available_for(self, mission_id=None):
        if self.status == "available":
            return True
        if mission_id is not None and self.reserved_by_mission == mission_id:
            return True
        return False

    # ¿ESTÁ FUERA DE SERVICIO?
    def is_out_of_service(self):
        return self.status == "out_of_service"

    # PONE EL RECURSO FUERA DE SERVICIO Y GUARDA EL ESTADO AL QUE DEBERÁ VOLVER
    def set_out_of_service(self, repair_at_step):
        self.status_before_failure = self.status
        self.status = "out_of_service"
        self.repair_at_step = repair_at_step
        self.reserved_by_mission = None   # LAS MISIONES AFECTADAS SE RE-PLANEAN APARTE

    # DEVUELVE EL RECURSO A SERVICIO
    def repair(self):
        self.status = "available"
        self.repair_at_step = None
        self.status_before_failure = None

    # APARTA EL RECURSO PARA UNA MISIÓN
    def reserve_for(self, mission):
        self.status = "is_reserved"
        self.reserved_by_mission = mission.id

    # LIBERA LA RESERVA. SOLO LA LIBERA SI LA MISIÓN QUE PIDE ES LA DUEÑA, PARA QUE UNA
    # MISIÓN NO PUEDA SOLTAR POR ERROR EL RECURSO DE OTRA.
    def release(self, mission_id=None):
        if mission_id is not None and self.reserved_by_mission != mission_id:
            return False
        self.reserved_by_mission = None
        if self.status == "is_reserved":
            self.status = "available"
        return True


# CLASE:      RACK AGENT
# ATRIBUTOS:  LOS DE RESOURCE AGENT + PALLET ID
class RackAgent(ResourceAgent):
    kind = "rack"

    def __init__(self, model, position):
        super().__init__(model, position)
        self.pallet_id = None

    # ¿ESTÁ OCUPADO EL RACK?
    def is_occupied(self):
        return self.pallet_id is not None

    # UN RACK CON PALLET NO SIRVE COMO DESTINO, AUNQUE SU STATUS DIGA "available"
    def is_available(self):
        return self.pallet_id is None and self.status == "available"

    def is_available_for(self, mission_id=None):
        if self.pallet_id is not None:
            return False
        return super().is_available_for(mission_id)

    # GUARDA UN PALLET EN EL RACK Y CIERRA LA RESERVA
    def store(self, pallet):
        self.pallet_id = pallet.pallet_id
        self.status = "occupied"
        self.reserved_by_mission = None
        pallet.status = "stored"

    # UN RACK REPARADO QUE CONSERVA SU PALLET VUELVE A "occupied", NO A "available"
    def repair(self):
        super().repair()
        if self.pallet_id is not None:
            self.status = "occupied"

    # AL SOLTAR LA RESERVA, UN RACK QUE TODAVÍA TIENE PALLET DEBE VOLVER A "occupied",
    # NO A "available". IMPORTA AL CANCELAR UNA MISIÓN TIPO 2 (RACK -> DOCK).
    def release(self, mission_id=None):
        ok = super().release(mission_id)
        if ok and self.pallet_id is not None and self.status == "available":
            self.status = "occupied"
        return ok

    # SACA EL PALLET DEL RACK Y LO DEVUELVE AL POOL DE DISPONIBLES
    def clear(self):
        self.pallet_id = None
        self.status = "available"
        self.reserved_by_mission = None


# CLASE: PRODUCTION LINE AGENT
class ProductionLineAgent(ResourceAgent):
    kind = "line"


# CLASE: TRUCK DOCK AGENT
class TruckDockAgent(ResourceAgent):
    kind = "dock"


# CLASE: MISSION
# Guarda los datos y tiempos de una misión concreta.
class Mission:
    def __init__(self, mission_id, mission_type, pickup_entity, dropoff_entity, pallet_id, step_created):
        self.id = mission_id
        self.type = mission_type
        self.pickup_entity = pickup_entity
        self.dropoff_entity = dropoff_entity
        self.pickup_loc = pickup_entity.access_cell
        self.dropoff_loc = dropoff_entity.access_cell
        self.pallet_id = pallet_id

        self.status = "pending"
        self.bids = {}
        self.assigned_to = None

        self.step_created = step_created
        self.step_accepted = None
        self.step_started = None
        self.step_completed = None

        self.reassign_count = 0
        self.last_reassign_step = -999
        self.reroute_count = 0

    def entities(self):
        return [self.pickup_entity, self.dropoff_entity]


# ============================================================
# CLASE: MISSION MANAGER
# ============================================================
# Responsabilidades:
# - generar o recibir misiones;
# - almacenar misiones pendientes;
# - publicar misiones disponibles;
# - registrar aceptación;
# - actualizar estados;
# - registrar misiones completadas;
# - mantener cancelaciones, reroutes y reasignaciones fuera del Environment.
class MissionManager:
    def __init__(self, model):
        self.model = model
        self.mission_counter = 0

        self.all_missions = []
        self.pending_missions = []
        self.available_missions = []
        self.completed_missions = []
        self.cancelled_missions = []

    # --------------------------------------------------------
    # CONSULTAS
    # --------------------------------------------------------
    def get_live_missions(self):
        return [
            m for m in self.all_missions
            if m.status not in ("completed", "cancelled")
        ]

    def get_available_missions(self):
        return [
            m for m in self.available_missions
            if m.status == "available"
        ]

    def get_assignment_for_agv(self, agv_id):
        for m in self.get_live_missions():
            if m.assigned_to == agv_id and m.status in ("assigned", "in_progress"):
                return m
        return None

    def has_assignment(self, agv_id):
        return self.get_assignment_for_agv(agv_id) is not None

    def get_eligible_agvs(self):
        return [
            agv for agv in self.model.agvs
            if (
                agv.state == "idle"
                and agv.mission is None
                and agv.battery > 20
                and not self.has_assignment(agv.agv_id)
            )
        ]

    # --------------------------------------------------------
    # GENERATE OR RECEIVE MISSIONS
    # --------------------------------------------------------
    def generate_or_receive_mission(self, mission=None):
        if mission is None:
            return self.generate_mission()
        return self.receive_mission(mission, publish=True)

    def receive_mission(self, mission, publish=False):
        if mission not in self.all_missions:
            self.all_missions.append(mission)

        mission.status = "pending"
        mission.assigned_to = None

        if mission not in self.pending_missions:
            self.pending_missions.append(mission)

        if publish:
            self.publish_available_missions()

        return mission

    # --------------------------------------------------------
    # GENERATE MISSION
    # --------------------------------------------------------
    def generate_mission(self):
        model = self.model

        free_lines = [
            ln for ln in model.lines
            if ln.is_available() and model._no_pallet_at(ln.position)
        ]
        free_docks = [
            d for d in model.docks
            if d.is_available() and model._no_pallet_at(d.position)
        ]
        free_racks = [r for r in model.racks if r.is_available()]
        occupied_racks = [
            r for r in model.racks
            if r.status == "occupied" and r.pallet_id is not None
        ]

        valid_mtypes = []
        if free_lines and free_racks:
            valid_mtypes.append(0)      # Production -> Rack
        if free_lines and free_docks:
            valid_mtypes.append(1)      # Production -> Dock
        if occupied_racks and free_docks:
            valid_mtypes.append(2)      # Rack -> Dock
        if free_docks and free_racks:
            valid_mtypes.append(3)      # Dock -> Rack

        if not valid_mtypes:
            return None

        mtype = model.random.choice(valid_mtypes)

        if mtype == 0:
            pickup = model.random.choice(free_lines)
            dropoff = model.random.choice(free_racks)
            pallet = model._add_pallet(pickup.position, status="waiting")

        elif mtype == 1:
            pickup = model.random.choice(free_lines)
            dropoff = model.random.choice(free_docks)
            pallet = model._add_pallet(pickup.position, status="waiting")

        elif mtype == 2:
            pickup = model.random.choice(occupied_racks)
            dropoff = model.random.choice(free_docks)
            pallet = next(
                (p for p in model.pallets if p.pallet_id == pickup.pallet_id),
                None
            )
            if pallet is None:
                return None

        else:  # mtype == 3
            pickup = model.random.choice(free_docks)
            dropoff = model.random.choice(free_racks)
            pallet = model._add_pallet(pickup.position, status="waiting")

        mission = Mission(
            self.mission_counter,
            mtype,
            pickup,
            dropoff,
            pallet.pallet_id,
            model.step_count
        )
        self.mission_counter += 1

        self.receive_mission(mission)
        self.publish_available_missions()
        return mission

    # --------------------------------------------------------
    # STORE / PUBLISH PENDING MISSIONS
    # --------------------------------------------------------
    def publish_available_missions(self):
        for mission in list(self.pending_missions):
            pickup = mission.pickup_entity
            dropoff = mission.dropoff_entity

            if pickup.access_cell is None or dropoff.access_cell is None:
                self.cancel_mission(mission, "recurso sin celda de acceso")
                continue

            # Reserva ambos extremos al publicarse.
            pickup.reserve_for(mission)
            dropoff.reserve_for(mission)

            pallet = next(
                (p for p in self.model.pallets if p.pallet_id == mission.pallet_id),
                None
            )
            if pallet is not None:
                pallet.status = "waiting"

            mission.status = "available"
            mission.assigned_to = None

            self.pending_missions.remove(mission)
            if mission not in self.available_missions:
                self.available_missions.append(mission)

            self.model.log.append(
                "[Step " + str(self.model.step_count) + "] Mission " +
                str(mission.id) + " published: type " + str(mission.type) +
                " (" + str(pickup.position) + " -> " + str(dropoff.position) + ")"
            )

    # --------------------------------------------------------
    # ACCEPTANCE / STATE UPDATES
    # --------------------------------------------------------
    def record_acceptance(self, mission, agv_id, bids=None):
        if mission.status != "available":
            return False

        if bids is not None:
            mission.bids = dict(bids)

        if mission in self.available_missions:
            self.available_missions.remove(mission)

        mission.assigned_to = agv_id
        mission.status = "assigned"
        mission.step_accepted = self.model.step_count

        self.model.log.append(
            "[Step " + str(self.model.step_count) + "] AGV-" +
            str(agv_id) + " accepts Mission " + str(mission.id)
        )
        return True

    def update_mission_state(self, mission, new_state):
        mission.status = new_state

        if new_state == "in_progress" and mission.step_started is None:
            mission.step_started = self.model.step_count

        if new_state == "available":
            mission.assigned_to = None
            if mission not in self.available_missions:
                self.available_missions.append(mission)

        return mission

    def release_assignment(self, mission, agv_id, reason=""):
        if mission.status in ("completed", "cancelled"):
            return False

        if mission.assigned_to not in (None, agv_id):
            return False

        mission.assigned_to = None
        mission.status = "available"
        mission.bids = {}

        if mission not in self.available_missions:
            self.available_missions.append(mission)

        self.model.log.append(
            "[Step " + str(self.model.step_count) + "] AGV-" +
            str(agv_id) + " released mission " + str(mission.id) +
            (" (" + reason + ")" if reason else "")
        )
        return True

    # --------------------------------------------------------
    # COMPLETED MISSIONS
    # --------------------------------------------------------
    def release_mission_reservations(self, mission):
        for entity in mission.entities():
            if entity is not None:
                entity.release(mission.id)

    def record_completed(self, mission, agv_id=None):
        if mission.status == "completed":
            return False

        self.release_mission_reservations(mission)

        if mission in self.pending_missions:
            self.pending_missions.remove(mission)
        if mission in self.available_missions:
            self.available_missions.remove(mission)

        mission.status = "completed"
        mission.step_completed = self.model.step_count

        if agv_id is not None:
            mission.assigned_to = agv_id

        if mission not in self.completed_missions:
            self.completed_missions.append(mission)

        return True

    # --------------------------------------------------------
    # HELPERS FOR FAILURES / REASSIGNMENT
    # --------------------------------------------------------
    def agv_of(self, mission):
        for agv in self.model.agvs:
            if agv.mission is mission:
                return agv

        if mission.assigned_to is not None:
            for agv in self.model.agvs:
                if agv.agv_id == mission.assigned_to:
                    return agv

        return None

    def find_alternative_dropoff(self, mission, failed_resource, allow_buffer=False):
        alternatives = [
            r for r in self.model.resources_of_kind(failed_resource.kind)
            if r is not failed_resource and r.is_available()
        ]

        if alternatives:
            return self.model.random.choice(alternatives)

        if allow_buffer:
            free_racks = [r for r in self.model.racks if r.is_available()]
            if free_racks:
                return self.model.random.choice(free_racks)

        return None

    def reroute_dropoff(self, mission, failed_resource):
        agv = self.agv_of(mission)
        carrying = agv is not None and agv.carrying_pallet is not None

        new_dropoff = self.find_alternative_dropoff(
            mission,
            failed_resource,
            allow_buffer=carrying
        )

        if new_dropoff is None:
            if not carrying:
                self.cancel_mission(mission, "sin destino alternativo")
            else:
                self.model.log.append(
                    "[Step " + str(self.model.step_count) + "] Mission " +
                    str(mission.id) + " sin destino alternativo, AGV espera"
                )
            return False

        failed_resource.release(mission.id)
        mission.dropoff_entity = new_dropoff
        mission.dropoff_loc = new_dropoff.access_cell
        new_dropoff.reserve_for(mission)
        mission.reroute_count += 1
        self.model.reroute_events += 1

        if agv is not None and agv.state == "delivering":
            agv.target = new_dropoff.access_cell
            agv.path = []
            agv.path_target = None

        self.model.log.append(
            "[Step " + str(self.model.step_count) + "] Mission " +
            str(mission.id) + " desviada: destino " +
            str(failed_resource.position) + " -> " + str(new_dropoff.position)
        )
        return True

    def cancel_mission(self, mission, reason=""):
        if mission.status == "cancelled":
            return False

        agv = self.agv_of(mission)
        if agv is not None and agv.mission is mission:
            agv.mission = None
            agv.target = None
            agv.path = []
            agv.path_target = None
            agv.blocked_steps = 0
            if agv.state in ("fetching", "idle"):
                agv.state = "idle"

        pallet = next(
            (p for p in self.model.pallets if p.pallet_id == mission.pallet_id),
            None
        )

        if pallet is not None and pallet.status != "transporting":
            if isinstance(mission.pickup_entity, RackAgent):
                pallet.status = "stored"
            else:
                pallet.status = "cancelled"
                if pallet.pos is not None:
                    self.model.grid.remove_agent(pallet)

        self.release_mission_reservations(mission)

        if mission in self.pending_missions:
            self.pending_missions.remove(mission)
        if mission in self.available_missions:
            self.available_missions.remove(mission)

        mission.status = "cancelled"
        mission.assigned_to = None

        if mission not in self.cancelled_missions:
            self.cancelled_missions.append(mission)

        self.model.cancel_events += 1
        self.model.log.append(
            "[Step " + str(self.model.step_count) + "] Mission " +
            str(mission.id) + " CANCELADA (" + reason + ")"
        )
        return True

    # --------------------------------------------------------
    # REASSIGNMENT RECORD
    # --------------------------------------------------------
    # IMPORTANTE:
    # MissionManager NO decide si una misión debe reasignarse y NO compara bids.
    # Esa negociación ocurre dentro de AGVAgent.negotiation().
    # Este método únicamente registra el resultado que los AGVs ya negociaron.
    def record_reassignment(
        self,
        mission,
        previous_agv_id,
        new_agv_id,
        bids=None,
        reason=""
    ):
        if mission.status not in ("assigned", "in_progress"):
            return False

        if bids is not None:
            mission.bids = dict(bids)
        else:
            mission.bids = {}

        mission.assigned_to = new_agv_id
        mission.status = "assigned"
        mission.reassign_count += 1
        mission.last_reassign_step = self.model.step_count
        self.model.reassign_events += 1

        previous_id = (
            "ninguno"
            if previous_agv_id is None
            else "AGV-" + str(previous_agv_id)
        )

        self.model.log.append(
            "[Step " + str(self.model.step_count) + "] REASIGNACIÓN: Mission " +
            str(mission.id) + " de " + previous_id + " a AGV-" +
            str(new_agv_id) + " (" + reason + ")"
        )
        return True

# CLASE:      AGVAGENT
# ATRIBUTOS:  ID, PREV_POS, TARGET, STATE, BATTERY, PALLET_ID, CARRYING_PALLET, MISSION, DISTANCE_TRAVELED, MISSIONS_COMPLETED

# ============================================================
# CLASE: PERSONS
# ============================================================
# Igual que los pallets: cada persona es de un solo uso, creada con un ID
# incremental que nunca se reutiliza (self.person_counter en el modelo) y
# nunca se elimina de self.persons (solo se marca is_active=False).
# Cada persona:
#   1) aparece en una puerta (izquierda o derecha, elegida al crearla),
#   2) va con A* a una casilla código 6 aleatoria,
#   3) espera 10 steps,
#   4) regresa a la MISMA puerta por la que entró,
#   5) permanece 1 step dentro de la puerta,
#   6) hace despawn (queda inactiva para siempre; una persona NUEVA podrá
#      spawnear después según el intervalo del modelo).
class Persons(mesa.Agent):
    def __init__(self, model, person_id, entry_door):
        super().__init__(model)

        self.person_id = person_id
        self.entry_door = entry_door

        self.state = "to_target"
        self.target = None

        self.path = []
        self.path_target = None

        self.wait_steps = 0
        self.exit_wait_steps = 0
        self.distance_traveled = 0
        self.orientation = 0
        self.is_active = True
        self.last_pos = None

    # CELDAS QUE UNA PERSONA NO PUEDE OCUPAR EN ESTE STEP
    def get_dynamic_obstacles(self):
        blocked = {
            agv.pos
            for agv in self.model.agvs
        }

        blocked.update({
            person.pos
            for person in self.model.persons
            if person != self and person.is_active
        })

        # Pallets estacionarios.
        for pallet in self.model.pallets:
            if (
                hasattr(pallet, "pos")
                and pallet.pos is not None
                and pallet.status != "transporting"
            ):
                blocked.add(pallet.pos)

        return blocked

    # ASIGNA UNA CASILLA DE CARGA/DESCARGA (CÓDIGO 6)
    def assign_loading_target(self):
        blocked = self.get_dynamic_obstacles()

        possible_targets = [
            cell
            for cell in UL_AREAS
            if cell not in blocked
        ]

        self.model.random.shuffle(possible_targets)

        for target in possible_targets:
            path = astar_person(
                self.pos,
                target,
                PERSON_MOVEMENT_GRAPH,
                blocked=blocked
            )

            if path is not None:
                self.target = target
                self.state = "to_target"
                self.path = []
                self.path_target = None

                self.model.log.append(
                    "[Step " + str(self.model.step_count) + "] Person-" +
                    str(self.person_id) + " target assigned: " + str(target)
                )
                return True

        self.target = None
        return False

    # AL LLEGAR AL OBJETIVO ESPERA 10 STEPS
    def start_waiting(self):
        self.state = "waiting"
        self.wait_steps = 10
        self.path = []
        self.path_target = None

        self.model.log.append(
            "[Step " + str(self.model.step_count) + "] Person-" +
            str(self.person_id) + " reached target " + str(self.pos) +
            " and will wait 10 steps"
        )

    # REGRESA EXACTAMENTE A LA MISMA CELDA DE PUERTA
    def start_returning(self):
        self.target = self.entry_door
        self.state = "to_exit"
        self.path = []
        self.path_target = None

        self.model.log.append(
            "[Step " + str(self.model.step_count) + "] Person-" +
            str(self.person_id) + " returning to original door " +
            str(self.entry_door)
        )

    # YA ENTRÓ EN EL CUADRADO DE LA PUERTA; DESAPARECE AL SIGUIENTE STEP
    def enter_exit_door(self):
        self.state = "at_exit"
        self.exit_wait_steps = 1
        self.path = []
        self.path_target = None

        self.model.log.append(
            "[Step " + str(self.model.step_count) + "] Person-" +
            str(self.person_id) + " entered exit door " +
            str(self.entry_door) + " and will despawn next step"
        )

    def step(self):
        # IR A LA CASILLA CÓDIGO 6
        if self.state == "to_target":
            if self.target is None:
                self.assign_loading_target()
                if self.target is None:
                    return

            if self.pos == self.target:
                self.start_waiting()
                return

            self.move_toward(self.target)

            if self.pos == self.target:
                self.start_waiting()

            return

        # ESPERAR 10 STEPS
        if self.state == "waiting":
            self.wait_steps -= 1

            if self.wait_steps <= 0:
                self.start_returning()

            return

        # REGRESAR A SU PUERTA ORIGINAL
        if self.state == "to_exit":
            if self.target is None:
                self.start_returning()

            if self.pos == self.target:
                self.enter_exit_door()
                return

            self.move_toward(self.target)

            if self.pos == self.target:
                self.enter_exit_door()

            return

        # PERMANECE UN STEP DENTRO DE LA PUERTA Y DESPUÉS DESAPARECE
        if self.state == "at_exit":
            self.exit_wait_steps -= 1

            if self.exit_wait_steps <= 0:
                self.model.despawn_person(self)

            return

    # MOVIMIENTO A* DE LA PERSONA
    def move_toward(self, target):
        if self.pos == target:
            return False

        blocked = self.get_dynamic_obstacles()

        if target in blocked:
            self.path = []
            self.path_target = None
            return False

        needs_recalculation = (
            not self.path
            or self.path_target != target
            or (
                len(self.path) > 1
                and self.path[1] in blocked
            )
        )

        if needs_recalculation:
            self.path = astar_person(
                self.pos,
                target,
                PERSON_MOVEMENT_GRAPH,
                blocked=blocked
            )
            self.path_target = target

            if not self.path or len(self.path) < 2:
                return False

        next_step = self.path[1]

        if next_step in blocked:
            self.path = []
            return False

        dx = next_step[0] - self.pos[0]
        dy = next_step[1] - self.pos[1]
        self.orientation = DIRECTION_TO_ORIENTATION.get((dx, dy), self.orientation)

        self.prev_pos = self.pos
        # BUGFIX: antes esta línea estaba duplicada (se llamaba move_agent dos veces
        # seguidas con el mismo destino). Con una sola llamada basta.
        self.model.grid.move_agent(self, next_step)
        self.distance_traveled += 1
        self.path.pop(0)

        return True

class AGVAgent(mesa.Agent):
    def __init__(self, model, agv_id):
        super().__init__(model)
        self.agv_id = agv_id
        self.prev_pos = None
        self.target = None
        self.state = "idle"
        self.battery = 100
        self.pallet_id = None
        self.carrying_pallet = None
        self.mission = None
        self.distance_traveled = 0
        self.missions_completed = 0
        self.path = []
        self.path_target = None
        self.blocked_steps = 0        # STEPS SEGUIDOS SIN PODER AVANZAR (ANTI-DEADLOCK)
        self.orientation = 0  # 0=arriba, 90=derecha, 180=abajo, 270=izquierda

    # FUNCIÓN: RELEASE_CURRENT_MISSION
    # DESCRIPCIÓN: DEVUELVE LA MISIÓN ACTUAL AL POOL DE SUBASTA. SOLO SE PUEDE SOLTAR SI EL AGV
    # NO TRAE EL PALLET ENCIMA: SI YA LO RECOGIÓ, LA MISIÓN SIGUE SIENDO SUYA Y LA RETOMARÁ AL
    # TERMINAR DE CARGAR. LAS RESERVAS NO SE TOCAN PORQUE SON DE LA MISIÓN, NO DEL AGV.
    # FUNCIÓN: RELEASE_CURRENT_MISSION
    # Devuelve la misión al MissionManager para volver a publicarla.
    def release_current_mission(self, reason=""):
        m = self.mission

        if m is None or self.carrying_pallet is not None:
            return False

        self.model.mission_manager.release_assignment(
            m,
            self.agv_id,
            reason
        )

        self.mission = None
        self.path = []
        self.path_target = None
        return True

    # FUNCIÓN: STEP
    # DESCRIPCIÓN: EN CADA STEP, VERIFICA EL ESTADO DEL AGV Y ACTÚA CONFORME A ESTE
    def step(self):
        if self.needs_charge() and self.state not in ("lowBattery", "charging"):
          self.release_current_mission("low battery")
          self.state = "lowBattery"
          self.target = None
          self.model.log.append("[Step " + str(self.model.step_count) + "] AGV-" + str(self.agv_id) + " low battery, rerouting to charger")

        if self.state == "idle":
            self.handle_idle()
        elif self.state == "fetching":
            self.handle_fetching()
        elif self.state == "delivering":
            self.handle_delivering()
        elif self.state == "lowBattery":
            self.handle_low_battery()
        elif self.state == "charging":
            self.handle_charging()

    # FUNCIÓN: HANDLE_IDLE
    # El AGV ya no publica bids aquí. La subasta ocurre en negotiation().
    # Aquí solo comprueba si la negociación le asignó una misión y empieza a ejecutarla.
    def handle_idle(self):
        manager = self.model.mission_manager
        won = manager.get_assignment_for_agv(self.agv_id)

        # CHECA LA BATERÍA
        if self.battery <= 20:
            if won:
                self.mission = won
                self.release_current_mission("battery low")
            self.state = "lowBattery"
            return

        # CON MISIÓN ASIGNADA
        if won:
            self.mission = won
            self.target = won.pickup_loc
            self.state = "fetching"
            manager.update_mission_state(won, "in_progress")
            self.model.log.append(
                "[Step " + str(self.model.step_count) + "] AGV-" +
                str(self.agv_id) + " starts Mission " + str(won.id) +
                ", moving to pickup"
            )
            return

    # FUNCIÓN: HANDLE_FETCHING
    # DESCRIPCIÓN: Gestiona la etapa de recolección del pallet. Al llegar al punto de recogida,
    # vincula el pallet al AGV y, si el origen era un rack, lo vacía y lo devuelve al pool.
    def handle_fetching(self):
        if self.battery <= 3:
            # SIN ESTO LA MISIÓN QUEDABA "in_progress" ASIGNADA A UN AGV QUE SE IBA A CARGAR
            # Y VOLVÍA A idle SIN PALLET: NADIE LA RETOMABA NUNCA.
            self.release_current_mission("battery critical")
            self.state = "lowBattery"
            self.target = None
            return

        if self.at_target():
            self.pallet_id = self.mission.pallet_id

            # "SE CARGA EL PALLET AL AGV"
            for p in self.model.pallets:
                if p.pallet_id == self.pallet_id:
                    self.carrying_pallet = p
                    break

            self.carrying_pallet.status = "transporting"
            self.model.grid.move_agent(self.carrying_pallet, self.pos)

            # EL ORIGEN QUEDA LIBRE EN CUANTO SE RETIRA EL PALLET.
            # ANTES ESTO SOLO SE HACÍA PARA MISIONES TIPO 2 Y BUSCANDO POR COORDENADA;
            # AHORA SE USA LA ENTIDAD DIRECTAMENTE Y APLICA A CUALQUIER TIPO DE ORIGEN.
            origin = self.mission.pickup_entity
            if isinstance(origin, RackAgent):
                origin.clear()
            else:
                origin.release(self.mission.id)

            self.state = "delivering"
            self.target = self.mission.dropoff_loc
            self.model.log.append("[Step " + str(self.model.step_count) + "] AGV-" + str(self.agv_id) + " picked up pallet, dropoff at " + str(self.target))
        else:
            self.move_toward(self.target)

    # FUNCIÓN: HANDLE DELIVERING
    # DESCRIPCIÓN: Gestiona la etapa de entrega. Al llegar, guarda el pallet en el rack destino
    # (dejándolo físicamente sobre la celda del rack) o lo marca como entregado si el destino
    # es un truck dock. Después libera las reservas de la misión y devuelve el AGV a idle.
    def handle_delivering(self):
        if self.battery <= 3:
            self.model.log.append("[Step " + str(self.model.step_count) + "] AGV-" + str(self.agv_id) + " low battery holding pallet, routing to charger")
            self.state = "lowBattery"
            self.target = None
            return

        if self.at_target():
            dest = self.mission.dropoff_entity

            if isinstance(dest, RackAgent):
                # EL PALLET SE MUEVE A LA CELDA FÍSICA DEL RACK, NO A LA CELDA DE ACCESO.
                # ESTE ERA EL ORIGEN DEL BUG: dropoff_loc ES LA CELDA OPERATIVA, ASÍ QUE
                # NINGÚN RACK COINCIDÍA NUNCA Y EL PALLET SE PERDÍA COMO "delivered".
                self.model.grid.move_agent(self.carrying_pallet, dest.position)
                dest.store(self.carrying_pallet)
            else:
                self.carrying_pallet.status = "delivered"
                self.model.grid.remove_agent(self.carrying_pallet)
                dest.release(self.mission.id)

            completed_mission = self.mission
            self.model.mission_manager.record_completed(completed_mission, self.agv_id)
            self.missions_completed += 1
            self.model.log.append("[Step " + str(self.model.step_count) + "] AGV-" + str(self.agv_id) + " delivered pallet to " + str(dest.position))
            self.pallet_id = None
            self.carrying_pallet = None
            self.mission = None
            self.state = "idle"
            self.target = None
        else:
            self.move_toward(self.target)

    # BUSCA EL CARGADOR ALCANZABLE MÁS CERCANO POR DISTANCIA REAL (A*), NO MANHATTAN
    def nearest_charger_real(self, pos, blocked=None):
        best_charger = None
        best_path = None
        best_dist = float("inf")

        for c in CHARGING_STATIONS:
            path = astar(pos, c, MOVEMENT_GRAPH, blocked=blocked)
            if path is not None:
                dist = len(path) - 1
                if dist < best_dist:
                    best_dist = dist
                    best_charger = c
                    best_path = path

        return best_charger, best_dist

    # CHEQUEO PROACTIVO DE BATERÍA - SE LLAMA EN CADA TICK DEL AGV, SIN IMPORTAR EL ESTADO
    def needs_charge(self):
        BATTERY_SAFETY_MARGIN = 7
        if self.state in ("charging", "lowBattery"):
            return False

        occupied = {a.pos for a in self.model.agvs if a != self}
        _, dist_to_charger = self.nearest_charger_real(self.pos, blocked=occupied)

        if dist_to_charger == float("inf"):
            return False

        return self.battery <= dist_to_charger + BATTERY_SAFETY_MARGIN

    def handle_low_battery(self):
        if self.target is None or self.target not in CHARGING_STATIONS:
            occupied = {a.pos for a in self.model.agvs if a != self}
            best_charger, _ = self.nearest_charger_real(self.pos, blocked=occupied)

            if best_charger is None:
                return

            self.target = best_charger
            self.model.log.append("[Step " + str(self.model.step_count) + "] AGV-" + str(self.agv_id) + " battery low (" + str(self.battery) + "%), charging")

        if self.pos == self.target:
            self.state = "charging"
        else:
            self.move_toward(self.target)

    # FUNCIÓN: HANDLE_CHARGING
    def handle_charging(self):
        self.battery = min(100, self.battery + 5)
        if self.battery >= 80:
            if self.pallet_id is not None and self.mission is not None:
                self.state = "delivering"
                self.target = self.mission.dropoff_loc
                self.model.log.append("[Step " + str(self.model.step_count) + "] AGV-" + str(self.agv_id) + " charged, resuming delivery")
            else:
                self.state = "idle"
                self.target = None
                self.model.log.append("[Step " + str(self.model.step_count) + "] AGV-" + str(self.agv_id) + " charged, back online")

    # DEVUELVE TRUE SI EL AGV TIENE UN DESTINO Y ESTÁ EXACTAMENTE EN ÉL
    def at_target(self):
        return self.target is not None and self.pos == self.target

    # CALCULA EL BID DEL AGV USANDO LA MISMA LÓGICA ORIGINAL:
    # distancia real A* + penalización por batería.
    # El BID MÁS PEQUEÑO es el mejor y gana la negociación.
    def calculate_bid(self, mission):
        path = astar(self.pos, mission.pickup_loc, MOVEMENT_GRAPH)

        if path is None:
            return float("inf")

        dist = len(path) - 1
        battery_penalty = (100 - self.battery) * 0.1

        return dist + battery_penalty

    # FUNCIÓN: NEGOTIATION
    # DESCRIPCIÓN:
    # - TODA decisión de asignación/reasignación vive en AGVAgent.
    # - Cada AGV calcula su propio bid con calculate_bid().
    # - La negociación recopila bids de los AGVs elegibles.
    # - El bid MÁS PEQUEÑO gana.
    # - MissionManager NO elige ganadores: solo registra el resultado.
    def negotiation(self):
        manager = self.model.mission_manager

        # ========================================================
        # 1) NEGOCIACIÓN DE MISIONES NUEVAS
        # ========================================================
        # Para no resolver la misma subasta varias veces en el mismo step,
        # el AGV elegible con menor ID actúa como coordinador de esa subasta.
        # La decisión sigue estando en AGVAgent.negotiation(), no en MissionManager.
        for mission in list(manager.get_available_missions()):
            eligible = manager.get_eligible_agvs()

            if not eligible:
                break

            coordinator = min(
                eligible,
                key=lambda agv: agv.agv_id
            )

            if coordinator is not self:
                continue

            bids = {}

            for agv in eligible:
                bid = agv.calculate_bid(mission)

                if bid == float("inf"):
                    continue

                bids[agv.agv_id] = bid

                self.model.log.append(
                    "[Step " + str(self.model.step_count) + "] AGV-" +
                    str(agv.agv_id) + " bid: " + str(round(bid, 2)) +
                    " on Mission " + str(mission.id)
                )

            if not bids:
                continue

            winner_id = min(
                bids,
                key=bids.get
            )

            # Los AGVs ya decidieron el ganador.
            # MissionManager solamente registra la aceptación.
            manager.record_acceptance(
                mission,
                winner_id,
                bids
            )

        # ========================================================
        # 2) RENEGOCIACIÓN DE LA MISIÓN ACTUAL
        # ========================================================
        # Una misión ya asignada NO es revisada por MissionManager.
        # El AGV que actualmente posee la misión decide si abre una
        # renegociación y recopila los bids de los AGVs libres.
        mission = self.mission

        if mission is None:
            return

        if mission.status not in ("assigned", "in_progress"):
            return

        if mission.assigned_to != self.agv_id:
            return

        if mission.reassign_count >= self.model.MAX_REASSIGNS:
            return

        if (
            self.model.step_count - mission.last_reassign_step
            < self.model.REASSIGN_COOLDOWN
        ):
            return

        # Una vez que el AGV ya tiene el pallet, la misión no se reasigna.
        if self.carrying_pallet is not None:
            return

        if self.state not in ("fetching", "idle"):
            return

        free_agvs = manager.get_eligible_agvs()

        if not free_agvs:
            return

        current_bid = self.calculate_bid(mission)

        bids = {
            self.agv_id: current_bid
        }

        best_agv = None
        best_bid = float("inf")

        for candidate in free_agvs:
            if candidate is self:
                continue

            bid = candidate.calculate_bid(mission)

            if bid == float("inf"):
                continue

            bids[candidate.agv_id] = bid

            self.model.log.append(
                "[Step " + str(self.model.step_count) + "] AGV-" +
                str(candidate.agv_id) + " reassign bid: " +
                str(round(bid, 2)) + " on Mission " +
                str(mission.id)
            )

            if bid < best_bid:
                best_bid = bid
                best_agv = candidate

        if best_agv is None:
            return

        # BID MENOR = MEJOR.
        improvement = current_bid - best_bid

        if improvement < self.model.REASSIGN_THRESHOLD:
            return

        # El AGV actual decide ceder la misión al ganador de la renegociación.
        # Primero se registra el resultado administrativo.
        changed = manager.record_reassignment(
            mission,
            self.agv_id,
            best_agv.agv_id,
            bids,
            "AGV-" + str(best_agv.agv_id) + " tiene bid " +
            str(round(improvement, 1)) + " puntos mejor"
        )

        if not changed:
            return

        # Después, el AGV que cedió limpia únicamente su estado local.
        # El nuevo AGV recogerá la asignación en handle_idle().
        self.mission = None
        self.target = None
        self.path = []
        self.path_target = None
        self.blocked_steps = 0

        if self.state in ("fetching", "idle"):
            self.state = "idle"

    # FUNCIÓN: YIELD_MOVE  (NUEVA)
    # DESCRIPCIÓN: MOVIMIENTO DE CORTESÍA PARA ROMPER BLOQUEOS MUTUOS. CUANDO DOS AGVs SE
    # ESPERAN ENTRE SÍ (UNO QUIERE ENTRAR A LA CELDA DEL OTRO Y VICEVERSA), NINGUNO CEDE Y
    # LA SIMULACIÓN SE CONGELA. AL PASAR EL UMBRAL, EL AGV SE APARTA A CUALQUIER CELDA
    # VECINA LIBRE, ROMPIENDO LA SIMETRÍA. PIERDE UN PASO Y 1% DE BATERÍA, PERO DESATASCA.
    def yield_move(self, occupied):
        restricted = UL_AREAS_SET | set(CHARGING_STATIONS)

        # Aunque el yield se usa para romper bloqueos AGV-AGV,
        # NUNCA puede apartarse hacia una celda ocupada por una persona.
        person_positions = {
            person.pos
            for person in self.model.persons
            if person.is_active
        }

        blocked = set(occupied) | person_positions

        candidatos = []
        for n in MOVEMENT_GRAPH.get(self.pos, []):
            if n in blocked:
                continue
            if n in restricted and n != self.target:
                continue
            candidatos.append(n)

        if not candidatos:
            return False

        preferidos = [c for c in candidatos if c != self.prev_pos]
        destino = self.model.random.choice(preferidos if preferidos else candidatos)

        dx = destino[0] - self.pos[0]
        dy = destino[1] - self.pos[1]
        self.orientation = DIRECTION_TO_ORIENTATION.get((dx, dy), self.orientation)

        self.prev_pos = self.pos
        self.model.grid.move_agent(self, destino)
        self.distance_traveled += 1
        self.battery = max(0, self.battery - 1)
        self.path = []
        self.path_target = None
        self.blocked_steps = 0

        if self.carrying_pallet is not None:
            self.model.grid.move_agent(self.carrying_pallet, self.pos)

        self.model.log.append(
            "[Step " + str(self.model.step_count) + "] AGV-" +
            str(self.agv_id) + " atascado, se aparta a " + str(destino)
        )
        return True

    def move_toward(self, target):
        if self.pos == target:
            self.blocked_steps = 0
            return False

        occupied_agvs = {
            agv.pos
            for agv in self.model.agvs
            if agv != self
        }

        person_positions = {
            person.pos
            for person in self.model.persons
            if person.is_active
        }

        # ========================================================
        # PRIORIDAD ABSOLUTA DE LAS PERSONAS
        # ========================================================
        # Si la siguiente casilla del camino del AGV está ocupada por
        # una persona, el AGV NO recalcula para adelantarla y NO hace
        # yield_move. Se queda quieto hasta que esa casilla se libere.
        #
        # Como las personas se actualizan antes que los AGVs en cada
        # step, si ambos querían entrar a una misma casilla vacía,
        # la persona entra primero y el AGV la encuentra ocupada.
        if (
            self.path
            and self.path_target == target
            and len(self.path) > 1
            and self.path[1] in person_positions
        ):
            return False

        # El anti-deadlock sigue aplicando únicamente a conflictos
        # con otros AGVs. Al apartarse, yield_move también evita personas.
        if self.blocked_steps >= self.model.STUCK_THRESHOLD:
            if self.yield_move(occupied_agvs):
                return True

        # Las personas NO se incluyen en el A* del AGV:
        # si una aparece sobre su ruta, el AGV espera a que pase en vez
        # de intentar ganarle el espacio o desviarse alrededor de ella.
        necesita_recalculo = (
            not self.path
            or self.path_target != target
            or (
                len(self.path) > 1
                and self.path[1] in occupied_agvs
            )
        )

        if necesita_recalculo:
            self.path = astar(
                self.pos,
                target,
                MOVEMENT_GRAPH,
                blocked=occupied_agvs
            )
            self.path_target = target

            if not self.path or len(self.path) < 2:
                return False

        next_step = self.path[1]

        # PERSONA > AGV: el AGV siempre espera.
        if next_step in person_positions:
            return False

        if next_step in occupied_agvs:
            return False


        dx = next_step[0] - self.pos[0]
        dy = next_step[1] - self.pos[1]
        self.orientation = DIRECTION_TO_ORIENTATION.get((dx, dy), self.orientation) # AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        self.prev_pos = self.pos
        self.model.grid.move_agent(self, next_step)
        self.distance_traveled += 1
        self.battery = max(0, self.battery - 1)
        self.path.pop(0)
        self.blocked_steps = 0

        if self.carrying_pallet is not None:
            self.model.grid.move_agent(self.carrying_pallet, self.pos)

        return True

class WarehouseModel(mesa.Model):
    MISSION_SPAWN_INTERVAL = 10

    # --- ANTI-DEADLOCK ---
    # STEPS SEGUIDOS SIN AVANZAR ANTES DE QUE UN AGV SE APARTE. CON 4 AGVs UNA ESPERA
    # LEGÍTIMA POR CRUCE SE RESUELVE EN 1-2 STEPS, ASÍ QUE 3 NO DISPARA DE MÁS Y ROMPE
    # LA SIMETRÍA RÁPIDO. MÁS ALTO ALARGA LOS ATASCOS; MÁS BAJO PROVOCA BAILE INÚTIL.
    STUCK_THRESHOLD = 3

    # --- AVERÍAS (out_of_service) ---
    FAILURE_PROB = 0.08       # PROBABILIDAD POR STEP DE QUE FALLE ALGÚN RECURSO (~1 CADA 12 STEPS)
    REPAIR_MIN = 15           # DURACIÓN MÍNIMA DE LA AVERÍA, EN STEPS
    REPAIR_MAX = 40           # DURACIÓN MÁXIMA
    MIN_IN_SERVICE = {"rack": 6, "line": 2, "dock": 2}   # INVARIANTE: NUNCA BAJAR DE ESTO

    # --- REASIGNACIÓN ---
    REASSIGN_THRESHOLD = 5    # EL RETADOR DEBE SER MEJOR POR AL MENOS ESTOS PASOS
    REASSIGN_COOLDOWN = 8     # STEPS MÍNIMOS ENTRE DOS REASIGNACIONES DE LA MISMA MISIÓN
    MAX_REASSIGNS = 2         # TOPE DE CAMBIOS DE AGV POR MISIÓN

    # FUNCIÓN: __INIT__
    # seed: FIJARLA HACE LA CORRIDA REPRODUCIBLE, ÚTIL PARA LA DEMO Y PARA DEPURAR.
    def __init__(self, n_agvs=4, n_persons=2, seed=None):
        super().__init__(seed=seed)
        if seed is not None:
            random.seed(seed)
        self.grid = mesa.space.MultiGrid(GRID_W, GRID_H, torus=False)
        self.step_count = 0
        self.pallets = []
        self.pallet_counter = 0
        self.mission_manager = MissionManager(self)
        self.log = []
        self.history = []
        self.failure_events = 0      # MÉTRICAS PARA LA DEMO
        self.repair_events = 0
        self.reassign_events = 0
        self.reroute_events = 0
        self.cancel_events = 0

        # RECURSOS: RACKS, LÍNEAS DE PRODUCCIÓN Y DOCKS.
        # AHORA LOS TRES SE INSTANCIAN COMO AGENTES Y SE REGISTRAN EN UN ÍNDICE COMÚN.
        # ANTES SOLO EXISTÍAN LOS RACKS; LAS LÍNEAS Y LOS DOCKS ERAN LISTAS DE COORDENADAS
        # SUELTAS Y SUS CLASES NUNCA SE USABAN.
        self.racks = []
        self.lines = []
        self.docks = []
        self.resources = {}        # position -> agente
        self.resource_by_access = {}   # access_cell -> agente

        for pos in RACK_POSITIONS:
            self._add_resource(RackAgent(self, pos), self.racks)

        for pos in PRODUCTION_LINE_ENDS:
            self._add_resource(ProductionLineAgent(self, pos), self.lines)

        for pos in TRUCK_DOCKS:
            self._add_resource(TruckDockAgent(self, pos), self.docks)

        # AGVs
        candidates = []
        for x in range(3, GRID_W - 1):
            if (x, 1) not in OBSTACLES:
                candidates.append((x, 1))

        start_positions = candidates[:n_agvs]

        self.agvs = []
        for i in range(n_agvs):
            agv = AGVAgent(self, i)
            self.agvs.append(agv)
            self.grid.place_agent(agv, start_positions[i])

        # ============================================================
        # PERSONS
        # ============================================================
        # Tratadas EXACTAMENTE como los pallets: self.persons nunca se vacía
        # (guarda a todas, activas e inactivas) y person_counter es un ID
        # incremental que nunca se reutiliza. El JSON de salida conserva así
        # el historial completo de todas las personas que existieron.
        self.persons = []
        self.person_counter = 0
        self.max_active_persons = n_persons   # cuántas pueden estar dentro del almacén a la vez
        self.person_spawn_interval = 20       # cada cuántos steps se intenta crear una persona nueva
        self.next_person_spawn_step = 10      # primer intento de spawn

        # AVISO DE RECURSOS INALCANZABLES POR LA GEOMETRÍA DEL LAYOUT
        inalcanzables = [r for r in self.resources.values() if r.status == "unreachable"]
        if inalcanzables:
            self.log.append("[Step 0] AVISO: " + str(len(inalcanzables)) +
                            " recursos inalcanzables por el layout, excluidos de las misiones: " +
                            str(sorted(r.position for r in inalcanzables)))

        # Initial mission at step 0, generated and published by MissionManager.
        self.mission_manager.generate_mission()

    # ============================================================
    # DESPAWN DE PERSONA
    # ============================================================
    # No se elimina de self.persons (igual que un pallet "delivered" sigue
    # en self.pallets): solo se marca inactiva y se retira del grid.
    def despawn_person(self, person):
        person.last_pos = list(person.pos) if person.pos is not None else person.last_pos
        person.is_active = False
        self.grid.remove_agent(person)

        self.log.append("[Step " + str(self.step_count) + "] Person-" + str(person.person_id) +
                        " left through door " + str(person.last_pos))

    # ============================================================
    # CONTROL DE SPAWN DE PERSONAS
    # ============================================================
    # Genérico: intenta crear una persona nueva cada person_spawn_interval
    # steps mientras haya cupo (activas < max_active_persons). Si la puerta
    # elegida está ocupada, reintenta en el siguiente step.
    def update_person_spawns(self):
        if self.step_count < self.next_person_spawn_step:
            return

        active_count = sum(1 for p in self.persons if p.is_active)
        if active_count >= self.max_active_persons:
            self.next_person_spawn_step = self.step_count + 1
            return

        side = self.random.choice(["left", "right"])
        created = self._add_person(side)

        self.next_person_spawn_step = (
            self.step_count + self.person_spawn_interval if created is not None
            else self.step_count + 1
        )

    def _add_resource(self, res, bucket):
        bucket.append(res)
        self.resources[res.position] = res
        if res.access_cell is not None:
            self.resource_by_access[res.access_cell] = res
        self.grid.place_agent(res, res.position)
        return res

    # FUNCIÓN: _ADD_PALLET
    def _add_pallet(self, position, status):
        pid = self.pallet_counter
        pallet = PalletAgent(self, pid, status)
        self.pallets.append(pallet)
        self.grid.place_agent(pallet, position)
        self.pallet_counter += 1
        return pallet

    # FUNCIÓN: _ADD_PERSON
    # DESCRIPCIÓN: MISMO PATRÓN QUE _ADD_PALLET. CREA UNA PERSONA CON ID NUEVO,
    # LA COLOCA EN UNA PUERTA LIBRE DEL LADO PEDIDO Y LA REGISTRA EN self.persons
    # (SIN QUE NUNCA SE ELIMINE DE AHÍ). DEVUELVE None SI NO HAY PUERTA LIBRE.
    def _add_person(self, side):
        occupied = {agv.pos for agv in self.agvs}
        occupied.update({p.pos for p in self.persons if p.is_active})
        for pallet in self.pallets:
            if hasattr(pallet, "pos") and pallet.pos is not None and pallet.status != "transporting":
                occupied.add(pallet.pos)

        candidate_doors = [d for d in DOORS if d[0] == (0 if side == "left" else GRID_W - 1)]
        available_doors = [d for d in candidate_doors if d not in occupied]
        if not available_doors:
            return None

        spawn_door = self.random.choice(available_doors)

        person_id = self.person_counter
        self.person_counter += 1

        person = Persons(self, person_id, spawn_door)
        person.is_active = True
        person.last_pos = list(spawn_door)

        self.persons.append(person)
        self.grid.place_agent(person, spawn_door)
        person.assign_loading_target()

        self.log.append("[Step " + str(self.step_count) + "] Person-" + str(person_id) +
                        " spawned at " + side + " door " + str(spawn_door))
        return person

    # FUNCIÓN: FIND_EMPTY_RANDOM_RACK
    # DESCRIPCIÓN: ELIGE UN RACK VACÍO, NO RESERVADO Y EN SERVICIO.
    def find_empty_random_rack(self):
        empty_racks = [r for r in self.racks if r.is_available()]
        if empty_racks:
            return random.choice(empty_racks)
        return None



    # AUXILIAR: ¿HAY ALGÚN PALLET VIVO SOBRE ESTA CELDA?
    def _no_pallet_at(self, pos):
        for p in self.pallets:
            if p.pos == pos and p.status not in ("delivered", "cancelled"):
                return False
        return True



    # ==================================================================================
    # BLOQUE 3: AVERÍAS (out_of_service) Y REPARACIONES
    # ==================================================================================

    # FUNCIÓN: RESOURCES_OF_KIND
    def resources_of_kind(self, kind):
        return [r for r in self.resources.values() if r.kind == kind]

    # FUNCIÓN: _CAN_FAIL
    # DESCRIPCIÓN: INVARIANTE DE SEGURIDAD. UN RECURSO SOLO PUEDE AVERIARSE SI, DESPUÉS DE
    # HACERLO, SU CLASE CONSERVA UN MÍNIMO DE UNIDADES EN SERVICIO **Y** AL MENOS UNA
    # UNIDAD LIBRE. ESTO ES LO QUE GARANTIZA QUE SIEMPRE EXISTA UN DESTINO ALTERNATIVO Y
    # QUE NINGÚN AGV SE QUEDE ATRAPADO CON UN PALLET QUE NO PUEDE SOLTAR EN NINGÚN LADO.
    def _can_fail(self, res):
        if not res.is_usable():
            return False

        hermanos = self.resources_of_kind(res.kind)
        en_servicio = [r for r in hermanos if r.is_usable() and r is not res]

        if len(en_servicio) < self.MIN_IN_SERVICE.get(res.kind, 1):
            return False

        # DEBE QUEDAR AL MENOS UN RECURSO LIBRE DE ESA CLASE PARA PODER DESVIAR
        if not any(r.is_available() for r in en_servicio):
            return False

        return True

    # FUNCIÓN: _MAYBE_FAIL_RESOURCE
    # DESCRIPCIÓN: GENERADOR ALEATORIO DE AVERÍAS. CADA STEP, CON PROBABILIDAD FAILURE_PROB,
    # SE AVERÍA UN RECURSO. PRIMERO SE ELIGE LA CLASE Y LUEGO LA UNIDAD, PORQUE HAY 72 RACKS
    # CONTRA 3 LÍNEAS Y 3 DOCKS: SI SE ELIGIERA UNIFORMEMENTE ENTRE LOS 78, CASI TODAS LAS
    # AVERÍAS CAERÍAN EN RACKS Y NUNCA SE VERÍA FALLAR UNA LÍNEA O UN DOCK EN LA DEMO.
    def _maybe_fail_resource(self):
        if self.random.random() >= self.FAILURE_PROB:
            return

        kinds = ["rack", "line", "dock"]
        self.random.shuffle(kinds)

        for kind in kinds:
            candidatos = [r for r in self.resources_of_kind(kind) if self._can_fail(r)]
            if candidatos:
                res = self.random.choice(candidatos)
                dur = self.random.randint(self.REPAIR_MIN, self.REPAIR_MAX)
                res.set_out_of_service(self.step_count + dur)
                self.failure_events += 1
                self.log.append("[Step " + str(self.step_count) + "] AVERÍA: " + res.kind +
                                " en " + str(res.position) + " fuera de servicio por " + str(dur) + " steps")
                self.on_resource_failed(res)
                return

    # FUNCIÓN: _PROCESS_REPAIRS
    def _process_repairs(self):
        for res in self.resources.values():
            if res.is_out_of_service() and res.repair_at_step is not None:
                if self.step_count >= res.repair_at_step:
                    res.repair()
                    self.repair_events += 1
                    self.log.append("[Step " + str(self.step_count) + "] REPARADO: " + res.kind +
                                    " en " + str(res.position) + " vuelve a servicio")

    # FUNCIÓN: ON_RESOURCE_FAILED
    # El Environment detecta la avería física, pero el MissionManager decide
    # cómo actualizar/cancelar/desviar las misiones afectadas.
    def on_resource_failed(self, res):
        afectadas = [
            m for m in self.mission_manager.get_live_missions()
            if m.pickup_entity is res or m.dropoff_entity is res
        ]

        for m in afectadas:
            if m.dropoff_entity is res:
                self.mission_manager.reroute_dropoff(m, res)

            if m.pickup_entity is res and m.status not in ("completed", "cancelled"):
                agv = self.mission_manager.agv_of(m)

                # Si ya lleva el pallet, el origen dejó de ser relevante.
                if agv is not None and agv.carrying_pallet is not None:
                    continue

                self.mission_manager.cancel_mission(
                    m,
                    "origen " + str(res.position) + " fuera de servicio"
                )







    # FUNCIÓN: STEP
    # ORDEN DE OPERACIONES:
    # 1) averías/reparaciones del entorno,
    # 2) personas (prioridad física),
    # 3) negociación Y renegociación distribuida entre AGVs,
    # 4) movimiento/acciones de AGVs,
    # 5) generación periódica de misiones por el MissionManager.
    def step(self):
        self._process_repairs()
        self._maybe_fail_resource()

        # PERSONAS PRIMERO: tienen prioridad física frente al AGV.
        for person in self.persons[:]:
            if person.is_active:
                person.step()

        self.update_person_spawns()

        # NEGOCIACIÓN: cada AGV posee su propia función negotiation().
        # El Environment solo dispara la fase; NO decide ni asigna misiones.
        for agv in self.agvs:
            agv.negotiation()

        # AGVs actúan después de la negociación.
        for agv in self.agvs:
            agv.step()

        # Generación periódica de nuevas misiones.
        if self.step_count > 0 and self.step_count % self.MISSION_SPAWN_INTERVAL == 0:
            self.mission_manager.generate_mission()

        self._snapshot()
        self.step_count += 1

    def _snapshot(self):
        agv_data = []
        for a in self.agvs:
            agv_data.append({
                "id": a.agv_id,
                "pos": list(a.pos) if a.pos is not None else None,
                "state": a.state,
                "pallet_id": a.pallet_id,
                "orientation": a.orientation,
                "battery": a.battery,
            })

        # PERSONAS: SIEMPRE TODAS, igual que los pallets — self.persons nunca las
        # elimina, así que basta conservar la última posición conocida (last_pos)
        # antes de que grid.remove_agent las deje con pos=None.
        person_data = []
        for person in self.persons:
            if person.is_active and person.pos is not None:
                person.last_pos = list(person.pos)
            person_data.append({
                "id": person.person_id,
                "pos": person.last_pos,
                "state": "active" if person.is_active else "inactive",
                "orientation": person.orientation,
            })

        rack_data = []
        for i, r in enumerate(self.racks):
            rack_data.append({
                "id": i,
                "pos": list(r.position),
                "pallet_id": r.pallet_id,
                "state": r.status,
            })

        dock_data = []
        for i, d in enumerate(self.docks):
            dock_data.append({
                "id": i,
                "pos": list(d.position),
                "pallet_id": self._pallet_id_at(d.position),
                "state": d.status,
            })

        prod_data = []
        for i, ln in enumerate(self.lines):
            prod_data.append({
                "id": i,
                "pos": list(ln.position),
                "pallet_id": self._pallet_id_at(ln.position),
                "state": ln.status,
            })

        # PALLETS: SIEMPRE TODOS, incluso delivered/cancelled — self.pallets nunca los borra,
        # así que solo hace falta conservar la última posición conocida antes de que
        # grid.remove_agent los deje con pos=None.
        pallet_data = []
        for p in self.pallets:
            if p.pos is not None:
                p.last_pos = list(p.pos)
            pallet_data.append({
                "id": p.pallet_id,
                "pos": getattr(p, "last_pos", None),
                "state": p.status,
            })

        self.history.append({
            "idx": self.step_count,
            "avgs": agv_data,
            "persons": person_data,
            "racks": rack_data,
            "docks": dock_data,
            "productionLines": prod_data,
            "pallets": pallet_data,
            "stats": {
                "completed": len(self.mission_manager.completed_missions),
                "failures": self.failure_events,
                "reroutes": self.reroute_events,
                "cancels": self.cancel_events,
                "reassigns": self.reassign_events,
            },
        })

    # HELPER: DEVUELVE EL ID DEL PALLET VIVO EN ESA POSICIÓN, O None.
    # DOCKS Y LÍNEAS NO GUARDAN pallet_id COMO LOS RACKS (SOLO RackAgent LO TIENE),
    # ASÍ QUE SE BUSCA POR COINCIDENCIA DE POSICIÓN ENTRE LOS PALLETS VIVOS.
    def _pallet_id_at(self, pos):
        for p in self.pallets:
            if p.pos == pos and p.status not in ("delivered", "cancelled"):
                return p.pallet_id
        return None

# # Visualization
#
# You may change these values to modify the number of agents and steps in the simulation respectively

N_AGVS = 4        # NÚMERO TOTAL DE AGVs
N_PERSONS = 2     # NÚMERO MÁXIMO DE PERSONAS ACTIVAS SIMULTÁNEAMENTE (se seguirán creando nuevas con IDs incrementales)
N_STEPS = 300     # NÚMERO TOTAL DE PASOS
SEED = 100        # SEMILLA FIJA: MISMA CORRIDA CADA VEZ (None = ALEATORIA)

import json
model = WarehouseModel(n_agvs=N_AGVS, n_persons=N_PERSONS, seed=SEED)
for _ in range(N_STEPS): model.step()

with open("simulation_frames.json", "w") as f:
    json.dump(model.history, f, indent=4)
    #print("Shape:", json_data.shape)
    #print("Dtype:", json_data.dtype)

import send_data
send_data.send()